name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build release binary
        run: cargo build --release

      - name: Rename binary with OS suffix
        run: |
          BIN_NAME=wf_codex
          PLATFORM=${{ matrix.os == 'ubuntu-latest' && 'linux' || 'macos' }}
          mv target/release/$BIN_NAME $BIN_NAME-$PLATFORM

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: wf_codex-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
